### ISSUE TITLE
Error: Deprecated option metadataUsedHelpers: Not required anymore as this is enabled by default

### ISSUE THREAD

**Issue by davis** [jspm/registry#410] opened 2015-06-05 20:13 UTC
should something deprecated prevent building??

```
     Building the single-file sfx bundle for src/main...

err  Error: Deprecated option metadataUsedHelpers: Not required anymore as this is enabled by default
         at File.normalizeOptions (evalmachine.<anonymous>:8271:15)
         at new File (evalmachine.<anonymous>:8237:22)
         at TransformerPipeline.transform (evalmachine.<anonymous>:12099:16)
         at /Users/davis/workspace/jspm-test-repo/node_modules/jspm/node_modules/systemjs-builder/compilers/es6.js:125:31
         at tryCatchReject (/Users/davis/workspace/jspm-test-repo/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
         at runContinuation1 (/Users/davis/workspace/jspm-test-repo/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
         at Fulfilled.when (/Users/davis/workspace/jspm-test-repo/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
         at Pending.run (/Users/davis/workspace/jspm-test-repo/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:821:13)
         at Scheduler._drain (/Users/davis/workspace/jspm-test-repo/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:97:19)
         at Scheduler.drain (/Users/davis/workspace/jspm-test-repo/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:62:9)
         at process._tickCallback (node.js:419:13)
```

# repro
clone this repo: https://github.com/davis/jspm-test-repo/tree/master
`npm i`
`npm run bundle`

**Comment by davis** [comment] 2015-06-05 20:14
going into `/Users/davis/workspace/jspm-test-repo/node_modules/jspm/node_modules/systemjs-builder/compilers/es6.js:125:31`

and changing metadataUsedHelpers from true to false allows build

**Comment by guybedford** [comment] 2015-06-05 20:52
Thanks for posting - yes this is a duplicate of https://github.com/jspm/jspm-cli/issues/809.

**Closed by guybedford** 2015-06-05 20:52 UTC

**Comment by davis** [comment] 2015-06-05 20:56
thanks!
