### ISSUE TITLE
Problem accessing a package from npm registry, fetched using jspm

### ISSUE THREAD

**Issue by adriatic** [jspm/registry#546] opened 2015-08-26 20:57 UTC
A **general question** is whether any npm package can be made accessible to an ES6 applicaton using jspm / system.js - or only those that are specifically listed in the the [registry](https://github.com/jspm/registry/blob/master/registry.json)? 

Then the **second, specific question** follows:
I used the command ``jspm install npm:stormpath`` which executed correctly as far as I can say. However, trying to run the very simple Aurelia application shown below:

import 'stormpath';

	export class App {

		constructor() {
			this.stormpath = require('stormpath');
		}

		activate() {

			let client = null;
			let homedir = (process.platform === 'win32') ? process.env.HOMEPATH : process.env.HOME;
			let keyfile = homedir + '/.stormpath/apiKey.properties';		
		}
	}

resulted with the following errors on Chrome console:

``
NFO [aurelia] Aurelia Started
system.src.js:3987 Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency.(anonymous function) @ system.src.js:3987(anonymous function) @ Config.js:8(anonymous function) @ Config.js:46(anonymous function) @ Config.js:48R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ Client.js:7(anonymous function) @ Client.js:304(anonymous function) @ Client.js:306R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath.js:8(anonymous function) @ stormpath.js:17R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath@0.11.0.js:1(anonymous function) @ stormpath@0.11.0.js:2R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987a @ system.src.js:3987execute @ system.src.js:3987b @ system.src.js:3987S @ system.src.js:3987p @ system.src.js:3987h @ system.src.js:3987(anonymous function) @ system.src.js:3987run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
system.src.js:3987 Uncaught Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency.
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Config.jsR @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ Client.js:7(anonymous function) @ Client.js:304(anonymous function) @ Client.js:306R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath.js:8(anonymous function) @ stormpath.js:17R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath@0.11.0.js:1(anonymous function) @ stormpath@0.11.0.js:2R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987a @ system.src.js:3987execute @ system.src.js:3987b @ system.src.js:3987S @ system.src.js:3987p @ system.src.js:3987h @ system.src.js:3987(anonymous function) @ system.src.js:3987run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
system.src.js:3987 Uncaught Uncaught Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency.
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Config.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Client.jsR @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath.js:8(anonymous function) @ stormpath.js:17R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath@0.11.0.js:1(anonymous function) @ stormpath@0.11.0.js:2R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987a @ system.src.js:3987execute @ system.src.js:3987b @ system.src.js:3987S @ system.src.js:3987p @ system.src.js:3987h @ system.src.js:3987(anonymous function) @ system.src.js:3987run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
system.src.js:3987 Uncaught Uncaught Uncaught Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency.
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Config.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Client.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/stormpath.jsR @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath@0.11.0.js:1(anonymous function) @ stormpath@0.11.0.js:2R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987a @ system.src.js:3987execute @ system.src.js:3987b @ system.src.js:3987S @ system.src.js:3987p @ system.src.js:3987h @ system.src.js:3987(anonymous function) @ system.src.js:3987run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
es6.promise.js:139 Unhandled promise rejection Uncaught Uncaught Uncaught Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency.
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Config.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Client.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/stormpath.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0.js
	Error loading http://localhost:9000/app.js
``

The relevant section of the config.js file also does not show anything strange
``
    "npm:stormpath@0.11.0": {
        "assert": "github:jspm/nodelibs-assert@0.1.0",
        "async": "npm:async@0.7.0",
        "buffer": "github:jspm/nodelibs-buffer@0.1.0",
        "crypto": "github:jspm/nodelibs-crypto@0.1.0",
        "deep-extend": "npm:deep-extend@0.4.0",
        "events": "github:jspm/nodelibs-events@0.1.1",
        "flat": "npm:flat@1.6.0",
        "fs": "github:jspm/nodelibs-fs@0.1.2",
        "glob": "npm:glob@3.2.11",
        "jwt-simple": "npm:jwt-simple@0.2.0",
        "memcached": "npm:memcached@0.2.8",
        "moment": "npm:moment@2.8.4",
        "njwt": "npm:njwt@0.2.2",
        "node-uuid": "npm:node-uuid@1.4.3",
        "os": "github:jspm/nodelibs-os@0.1.0",
        "path": "github:jspm/nodelibs-path@0.1.0",
        "process": "github:jspm/nodelibs-process@0.1.1",
        "properties-parser": "npm:properties-parser@0.2.3",
        "redis": "npm:redis@0.12.1",
        "request": "npm:request@2.40.0",
        "systemjs-json": "github:systemjs/plugin-json@0.1.0",
        "underscore": "npm:underscore@1.5.2",
        "underscore.string": "npm:underscore.string@2.3.3",
        "url": "github:jspm/nodelibs-url@0.1.0",
        "util": "github:jspm/nodelibs-util@0.1.0"
      },
``

**Comment by guybedford** [comment] 2015-08-27 09:14
Yes, in general we do support npm registry installs, although the compatibility is not 100%. Usually the rule here is that the project should support Browserify.

For cases like this one that don't work easily, usually an override can be added to make it work. The issue you're having can be resolved with configuration fine.

That said, I'm not sure this package supports use in the browser though via Browserify, so it won't be supported in jspm then. (It seems to use APIs like `fs.existsSync` which can't work in the browser).

**Comment by adriatic** [comment] 2015-08-27 09:41
Incredibly quick response Guy - and you do work odd hours. I always wondered how could such complex software as the whole jspm/jpm stack work; now I feel safer seeing the amount of compassion present :-)

Allow me one more question: this same identical package works just fine in the "old" context (pre-ES6) fetched with bower. This indicates that I do not really know enough about Browserify requirements, so what means

    Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency

I see it as a "failed error recovery" - the problem happened higher in the stack, making this error diagnosis incorrect.

Would you mind giving me a hint on "The issue you're having can be resolved with configuration fine."?

**Comment by guybedford** [comment] 2015-08-27 10:37
Sure, no problem at all. Ah, so I think you want to be installing `jspm install npm:stormpath-js` from https://github.com/stormpath/stormpath.js here - the client version of the library.

I just tested it out and there was one issue in not finding `base64`, which was set as a dependency.

This can be then made to work via:

```
  jspm install npm:stormpath-js -o "{map:{'base64':'Base64'}}"
```

It could be worth posting an issue there that the require at https://github.com/stormpath/stormpath.js/blob/master/lib/utils.js#L2 should be to `Base64` not `base64`, or we can commit this override into the jspm registry, which will allow it to be shared for all future installs of this package (https://github.com/jspm/registry/).

**Comment by adriatic** [comment] 2015-08-27 11:05
You are unbelievable, Guy. I will talk to Stormpath folks and your recommendation about committing this override int jspm registry is a good one regardless. Let me do that as well, to say at least a small thank you!.

Perhaps this short exchange can give you some ideas on how to improve the error messages (meaning jspm runtime behavior) to save you from such pedestrian tasks I assigned to you today :-)

Alternatively, you may consider documenting the process it took you to start with

   ``"Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency"``

and end with 

``jspm install npm:stormpath-js -o "{map:{'base64':'Base64'}}"``

This has to do with the old saying "teach people how to fish instead of trying to feed them" :-)

**Comment by guybedford** [comment] 2015-08-28 12:58
Sure, you're welcome! Getting from `npm:stormpath` to `npm:stormpath-js` is likely a documentation issue with Stormpath actually. Note also that https://github.com/stormpath/stormpath.js says to install `npm:stormpath.js` in its readme which doesn't exist (which may also explain the low download numbers at https://www.npmjs.com/package/stormpath-js!). I'm sure they'd appreciate hearing these things if you're interested in following them up.

As for the `{map:{'base64':'Base64'}}` I did actually create an issue to investigate the root cause in https://www.npmjs.com/package/stormpath-js here.

Having high-level messages for low-level bugs is a long-term goal, which I think will improve as we're able to put more effort into automatic package understanding / testing and reporting, which is the major area to focus on to improve usability of jspm, once the rest of the project is stable. For now it is still a shortest-path evolution of sorts though, so thanks for bearing any rough edges.

**Closed by guybedford** 2015-08-28 12:58 UTC

**Comment by adriatic** [comment] 2015-08-28 19:58
Hi Guy

For last two days I was out of office being very anxious to come back and try your remedy. Now I did - and got the same results, despite trying to be very careful not to make some silly pilot error. 

**First the most important stuff :-)**:

I genuinely admire the complexity and importance of jspm and even more your cool and brave decision to "help the world" with something like that. So, I would really love to be of some help to you (in addition to bug you to help me with this). In order to of any use, I decided to learn everything that exists about jspm (in terms of the documentation - not the code as that would be utterly silly to do having no understanding about npm package management other that what I had to know as a user). 

Once I get to be reasonably informed about jspm, I could be your proxy for "Aurelia Developers" (note that this is a different category than "Aurelia Core Team" - if that would help you. Such proxy role would mostly include handling most of the user level jspm issues in the context of Aurelia - see http://blog/Aurelia-Guides.com which is my project designed to enhance Aurelia documentation

----
**Now here is what I did to implement your advice for a fix**

1 Deleted the dependency on Stormpath in ``package.json``:

```
{
  "jspm": {
    "directories": {},
    "dependencies": {
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.16.0",
      "aurelia-framework": "github:aurelia/framework@^0.15.0"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.21",
      "babel-runtime": "npm:babel-runtime@^5.8.20",
      "core-js": "npm:core-js@^1.0.0"
    } 
  },
  "devDependencies": {
    "browser-sync": "^2.8.2",
    "gulp": "^3.9.0"
  }
}


```

2 Deleted the actual Stormpath package in jspm/npm folder

3 run the command `` jspm install npm:stormpath-js -o "{map:{'base64':'Base64'}}"``

```
warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
     Looking up npm:stormpath-js
     Updating registry cache...
     Looking up npm:Base64
     Looking up github:systemjs/plugin-json
     Looking up github:jspm/nodelibs-process
     Looking up npm:stormpath
     Looking up npm:process
ok   Installed stormpath-js as npm:stormpath-js@^0.2.0 (0.2.0)
     Installed Forks

                                 npm:Base64 0.2.1 0.3.0
                                  npm:async 0.7.0 0.9.2
                                npm:core-js 0.9.18 1.1.1
                                npm:process 0.10.1 0.11.1

     To inspect individual package constraints, use jspm inspect registry:name.


ok   Install complete.
```

5 The package.json now looks as it should (including the mapping of "base64" to "base64":

```
{
  "jspm": {
    "directories": {},
    "dependencies": {
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.16.0",
      "aurelia-framework": "github:aurelia/framework@^0.15.0",
      "stormpath-js": "npm:stormpath-js@^0.2.0"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.21",
      "babel-runtime": "npm:babel-runtime@^5.8.20",
      "core-js": "npm:core-js@^1.0.0"
    },
    "overrides": {
      "npm:stormpath-js@0.2.0": {
        "map": {
          "base64": "Base64"
        }
      }
    }
  },
  "devDependencies": {
    "browser-sync": "^2.8.2",
    "gulp": "^3.9.0"
  }
}
```

4  run the command ``gulp serve``


5 run the app by pointing the browser to ``http://localhost:9000``

Got the crash similar to before

```
DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.14.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.14.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.14.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.14.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/history-browser@0.7.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/history-browser@0.7.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/templating-router@0.15.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/templating-router@0.15.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/event-aggregator@0.7.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/event-aggregator@0.7.0.
aurelia-logging-console.js:46 INFO [aurelia] Aurelia Started
system.src.js:3987 Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency.(anonymous function) @ system.src.js:3987(anonymous function) @ Config.js:8(anonymous function) @ Config.js:46(anonymous function) @ Config.js:48R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ Client.js:7(anonymous function) @ Client.js:304(anonymous function) @ Client.js:306R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath.js:8(anonymous function) @ stormpath.js:17R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath@0.11.0.js:1(anonymous function) @ stormpath@0.11.0.js:2R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987a @ system.src.js:3987Promise.all.then.execute @ system.src.js:3987b @ system.src.js:3987S @ system.src.js:3987p @ system.src.js:3987h @ system.src.js:3987(anonymous function) @ system.src.js:3987run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
system.src.js:3987 Uncaught Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency.
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Config.jsR @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ Client.js:7(anonymous function) @ Client.js:304(anonymous function) @ Client.js:306R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath.js:8(anonymous function) @ stormpath.js:17R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath@0.11.0.js:1(anonymous function) @ stormpath@0.11.0.js:2R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987a @ system.src.js:3987Promise.all.then.execute @ system.src.js:3987b @ system.src.js:3987S @ system.src.js:3987p @ system.src.js:3987h @ system.src.js:3987(anonymous function) @ system.src.js:3987run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
system.src.js:3987 Uncaught Uncaught Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency.
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Config.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Client.jsR @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath.js:8(anonymous function) @ stormpath.js:17R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath@0.11.0.js:1(anonymous function) @ stormpath@0.11.0.js:2R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987a @ system.src.js:3987Promise.all.then.execute @ system.src.js:3987b @ system.src.js:3987S @ system.src.js:3987p @ system.src.js:3987h @ system.src.js:3987(anonymous function) @ system.src.js:3987run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
system.src.js:3987 Uncaught Uncaught Uncaught Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency.
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Config.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Client.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/stormpath.jsR @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987i @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ stormpath@0.11.0.js:1(anonymous function) @ stormpath@0.11.0.js:2R @ system.src.js:3987s.metadata.execute @ system.src.js:3987u @ system.src.js:3987a @ system.src.js:3987Promise.all.then.execute @ system.src.js:3987b @ system.src.js:3987S @ system.src.js:3987p @ system.src.js:3987h @ system.src.js:3987(anonymous function) @ system.src.js:3987run @ es6.promise.js:91(anonymous function) @ es6.promise.js:105module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
es6.promise.js:139 Unhandled promise rejection Uncaught Uncaught Uncaught Uncaught TypeError: Module /jspm_packages/npm/stormpath@0.11.0/lib/config.json not declared as a dependency.
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Config.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/Client.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0/lib/stormpath.js
	Evaluating http://localhost:9000/jspm_packages/npm/stormpath@0.11.0.js
	Error loading http://localhost:9000/app.js(anonymous function) @ es6.promise.js:139module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
```

So, while it might be that my attempt to use the Stormpath Client from the Aurelia app made a step forward - I remain clueless about what is happening here. 

Attached is this project without the jspm-packages and node-modules folders.

[SimpleStormpath.zip | uploaded via ZenHub](https://files.zenhub.io/55e0bd46c1081b130f47269d)

**Comment by guybedford** [comment] 2015-09-02 09:51
Thanks @adriatic, the hardest part at the moment is managing expectations while the project is still evolving. A lot of users are now coming to jspm without understanding the surrounding technologies like legacy module formats, globals, shims, npm packages, RequireJS etc etc. And yes it is a lot to learn. The nice thing is that jspm can cover up a lot of these things so users don't need to think about them, but when it breaks, there is certainly a deep path to understand the root cause. This will get better as more existing libraries work to support jspm, but at the moment can still be a bit painful unfortunately, and I don't personally have the resources to do much more than just maintain the core project. The only way that workflows around jspm get better is through community projects and contributors working on guides, plugins, overrides, bug reports etc etc. Any help with this is always incredibly welcome, as well as suggestions for how I can better accommodate these efforts. There has been some discussion about better curating the community resources perhaps with an improved version of https://github.com/jspm/jspm-cli/wiki/Third-Party-Resources maintained on the website itself.

For your issue I think this may just be a naming issue - changing your `System.import` or `import` statement to load `stormpath-js` instead of `stormpath`, the server package.

**Comment by adriatic** [comment] 2015-09-02 14:29
Guy, I like the idea of curating the community via https://github.com/jspm/jspm-cli/wiki/Third-Party-Resources a lot and am interested in offering as much help as you can take to get this going. My motivation is simple: I love Aurelia and everything around it and I want to use it in my future work. As I do not want to spend infinite amounts of time figuring something out that should be well documented (in the ideal case of course), I decided to spend as much time as it takes to help "bringing order" in this environment by offering my interpretation of the existing documents, hoping to iron out the points of "friction"
